query ($goodsParams:ScrollQueryGoods={kind:'1',subkind:'2',status:'4',pageSize:10}, $userid:Long, $orderParams:ScrollQueryGoodsOrder,$userseq:Long){
	
	goods(goodsseq:1){
			status
			ownerseq
			... total
			... on TPGoods{
				ctime:createtime
			}
	}
	#queryGoodsList
	goodsList(params:$goodsParams){
			status
			ownerseq
			... total
	}
	
	
	goodsOrders(params:$orderParams){
			orderseq
			buyerseq
			ownerseq
			paytime
			goodsseq
			goodsname
	}
	
	goodsReviews(params:$orderParams){
			orderseq
			buyerseq
			ownerseq
			goodsreview
	}
	
	vipuser(userseq:$userseq){
		... userInfo
	}
	
}

fragment userInfo on VIP{
	vipno
}

fragment total on TPGoods{
	goodsseq
	goodsname
	amount
	count
	postfee
}